import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { AnimatedSection } from "@/components/AnimatedSection";

const faqData = [
  {
    id: "item-1",
    question: "What makes Akuma's AI-powered designs unique?",
    answer: "Our AI studio uses advanced machine learning to generate one-of-a-kind monster-inspired designs based on your preferences. Each design is unique and can be customized with different elements, colors, and styles to match your personal aesthetic."
  },
  {
    id: "item-2",
    question: "What materials do you use for your streetwear?",
    answer: "We use premium materials including 100% organic cotton, sustainable cotton blends, water-resistant fabrics, and eco-friendly materials. All our products are ethically sourced and manufactured to the highest quality standards."
  },
  {
    id: "item-3",
    question: "How does the sizing work for Akuma products?",
    answer: "Our products follow standard streetwear sizing with an oversized fit philosophy. We recommend checking our size guide for specific measurements. Most customers prefer to size down for a more fitted look or stay true to size for the intended oversized aesthetic."
  },
  {
    id: "item-4",
    question: "What is your return and exchange policy?",
    answer: "We offer a 30-day return policy for unworn items in original condition. AI-customized products have a 14-day return window. Exchanges are free within the first 14 days, and we provide prepaid return labels for defective items."
  },
  {
    id: "item-5",
    question: "How long does it take to create and ship AI-customized items?",
    answer: "AI-generated designs are created instantly, but production takes 3-5 business days for customized items. Standard shipping is 5-7 business days, while express shipping is 2-3 business days. You'll receive tracking information once your order ships."
  },
  {
    id: "item-6",
    question: "Do you ship internationally?",
    answer: "Yes, we ship worldwide! International shipping typically takes 7-14 business days depending on location. Customs fees may apply and are the responsibility of the customer. We use reliable international carriers with full tracking."
  },
  {
    id: "item-7",
    question: "How do I care for my Akuma streetwear?",
    answer: "For best results, machine wash cold with like colors, use mild detergent, and hang dry or tumble dry on low heat. Avoid bleach and fabric softeners. For items with special prints or AI designs, wash inside out to preserve the graphics."
  },
  {
    id: "item-8",
    question: "Can I request custom monster designs not generated by AI?",
    answer: "While our AI studio covers most design preferences, we do accept custom design requests for bulk orders (10+ items). Contact our design team with your ideas, and we'll work with you to create something unique that fits the Akuma aesthetic."
  }
];

const FAQ = () => {
  return (
    <section className="py-16 sm:py-20 relative overflow-hidden">
      {/* Background effects */}
      <div className="absolute inset-0 cyber-grid opacity-20" />
      <div className="absolute top-20 right-20 w-64 h-64 bg-primary/5 rounded-full blur-3xl" />
      <div className="absolute bottom-20 left-20 w-64 h-64 bg-secondary/5 rounded-full blur-3xl" />
      
      <div className="container mx-auto px-4 sm:px-6 relative z-10">
        <AnimatedSection className="text-center space-y-4 mb-12 sm:mb-16">
          <Badge className="bg-accent/20 text-accent border-accent/30 neon-glow animate-pulse">
            Help Center
          </Badge>
          <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-orbitron font-black">
            <span className="gradient-text relative inline-block">
              FREQUENTLY ASKED QUESTIONS
              <div className="absolute -bottom-2 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-primary to-transparent" />
            </span>
          </h2>
          <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto font-rajdhani">
            Everything you need to know about Akuma streetwear and our AI-powered design process
          </p>
        </AnimatedSection>

        <AnimatedSection animation="fade-up" delay={200} className="max-w-4xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqData.map((faq, index) => (
              <AccordionItem
                key={faq.id}
                value={faq.id}
                className="bg-card/50 backdrop-blur-sm border border-border/50 rounded-lg px-6 hover:border-primary/50 transition-all duration-300 group relative overflow-hidden"
              >
                <div className="absolute inset-0 bg-gradient-to-r from-primary/5 to-secondary/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <AccordionTrigger className="text-left font-orbitron font-semibold text-base sm:text-lg hover:text-primary transition-colors relative z-10">
                  <span className="flex items-center gap-3">
                    <span className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold group-hover:bg-primary/20 transition-colors">
                      {index + 1}
                    </span>
                    {faq.question}
                  </span>
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground font-rajdhani text-base sm:text-lg leading-relaxed ml-11 relative z-10">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </AnimatedSection>

        <AnimatedSection animation="fade-in" delay={400} className="text-center mt-12 sm:mt-16">
          <div className="bg-card/30 backdrop-blur-sm border border-primary/20 rounded-lg p-6 sm:p-8 max-w-2xl mx-auto">
            <h3 className="font-orbitron font-bold text-xl sm:text-2xl mb-4 gradient-text">
              Still Have Questions?
            </h3>
            <p className="text-muted-foreground font-rajdhani mb-6">
              Can't find what you're looking for? Our support team is here to help you unleash your inner monster.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="mailto:support@akuma-streetwear.com"
                className="inline-flex items-center justify-center px-6 py-3 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors font-rajdhani font-semibold"
              >
                Email Support
              </a>
              <a
                href="#"
                className="inline-flex items-center justify-center px-6 py-3 border border-primary text-primary rounded-lg hover:bg-primary hover:text-primary-foreground transition-colors font-rajdhani font-semibold"
              >
                Live Chat
              </a>
            </div>
          </div>
        </AnimatedSection>
      </div>
    </section>
  );
};

export default FAQ;